#!/bin/sh
CURL='curl --retry 3 --retry-delay 0 --silent --fail'
IP_ADDR=`$CURL http://169.254.169.254/1.0/meta-data/local-ipv4`
CONF=/etc/murakumo.yml

if [ $? -ne 0 -o -z "$IP_ADDR" ]; then
  exit 1
fi

if [ `grep ^host $CONF | egrep "host: $IP_ADDR\b" | wc -l` -eq 1 ]; then
  exit
fi

## gets a host name from user data.
#HOSTNAME=`$CURL http://169.254.169.254/1.0/user-data`

## gets a host name from name tag.
#export JAVA_HOME=/usr/java/default
#export EC2_HOME=/opt/ec2-api-tools
#EC2_PRIVATE_KEY=
#EC2_CERT=
#REGION=ap-northeast-1
#EC2DIN=$EC2_HOME/bin/ec2-describe-instances
#HOSTNAME=`$EC2DIN -K $EC2_PRIVATE_KEY -C $EC2_CERT --region $REGION -F "private-ip-address=$IP_ADDR" | awk -F'\t' '$1 == "TAG" && $4 == "Name" {print $5}'`

HOSTNAME=`$CURL http://169.254.169.254/1.0/meta-data/hostname`

if [ $? -ne 0 -o -z "$HOSTNAME" ]; then
  exit 1
fi

sed -i.bak -r "s|^host:.*|host: $IP_ADDR, $HOSTNAME|" /etc/murakumo.yml
